name: katiecordescodes-adventofcode-frontend

services:
  nextjs:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_IDENTIFIER}.rule=Host(`${SITE_URL}`)"
      - "traefik.http.routers.${TRAEFIK_IDENTIFIER}.entryPoints=web"
      - "traefik.http.routers.${TRAEFIK_IDENTIFIER}.service=${TRAEFIK_IDENTIFIER}"
      - "traefik.http.services.${TRAEFIK_IDENTIFIER}.loadbalancer.server.port=3000"
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true
  default:
    name: katiecordescodes-adventofcode