name: Deploy to production

# Required secrets
# DOCKERHUB_USER
# DOCKERHUB_TOKEN
# DEPLOY_PATH
# SSH_HOST
# SSH_USER
# SSH_KEY

on:
  push:
    branches:
      - main

env:
  DOCKER_COMPOSE_FILES: -f compose.yaml -f compose.prod.yaml -f compose.ssl.yaml
  DOCKER_COMPOSE_FILES_LIST: "compose.yaml,compose.prod.yaml,compose.ssl.yaml"
  DOCKER_COMPOSE_PROJECT: katiecordescodes-adventofcode-frontend
  SERVICE_NAME: nextjs

jobs:
  build:
    uses: katharinegillis/github-workflows/.github/workflows/ci-build.yml@main
    with:
      DOCKER_COMPOSE_FILES: $DOCKER_COMPOSE_FILES
      DEPLOY_ENVIRONMENT: Production
      ENV_FILE: .env.prod
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-env:
    runs-on: ubuntu-latest
    environment: Production
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the environment file
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: .env.prod
          output: .env

      - name: Ensure deploy path exists
        uses: appleboy/ssh-action@master
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DEPLOY_PATH
          script: mkdir -p $DEPLOY_PATH

      - name: Deploy the environment file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".env"
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Sleep to reset ssh connection
        run: sleep 30

  deploy-single:
    needs: ['build', 'deploy-env']
    uses: katharinegillis/github-workflows/.github/workflows/ci-deploy-single.yml@main
    with:
      DOCKER_COMPOSE_FILES_LIST: $DOCKER_COMPOSE_FILES_LIST
      DEPLOY_ENVIRONMENT: Production
      DOCKER_COMPOSE_PROJECT: $DOCKER_COMPOSE_PROJECT
      SERVICE_NAME: $SERVICE_NAME
      DOCKER_COMPOSE_FILES: $DOCKER_COMPOSE_FILES
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
