name: Deploy to production

# Required secrets
# DOCKERHUB_USER
# DOCKERHUB_TOKEN
# DEPLOY_PATH
# SSH_HOST
# SSH_USER
# SSH_KEY

on:
  push:
    branches:
      - main

env:
  DOCKER_COMPOSE_FILES: -f compose.yaml -f compose.prod.yaml -f compose.ssl.yaml
  DOCKER_COMPOSE_FILES_LIST: "compose.yaml,compose.prod.yaml,compose.ssl.yaml"
  DOCKER_COMPOSE_PROJECT: katiecordescodes-adventofcode-frontend
  SERVICE_NAME: nextjs

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the environment file
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: .env.prod
          output: .env

      - name: Build the image(s)
        run: docker compose ${{ env.DOCKER_COMPOSE_FILES }} build

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push up the image(s)
        run: docker compose ${{ env.DOCKER_COMPOSE_FILES }} push

  deploy-env:
    runs-on: ubuntu-latest
    environment: Production
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the environment file
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: .env.prod
          output: .env

      - name: Ensure deploy path exists
        uses: appleboy/ssh-action@master
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DEPLOY_PATH
          script: mkdir -p $DEPLOY_PATH

      - name: Deploy the environment file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".env"
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Sleep to reset ssh connection
        run: sleep 30

  deploy-single:
    needs: ['build', 'deploy-env']
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Copy up the deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".deploy/deploy-single.sh,${{ env.DOCKER_COMPOSE_FILES_LIST }}"
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Deploy the application
        uses: appleboy/ssh-action@master
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DOCKER_COMPOSE_PROJECT: $DOCKER_COMPOSE_PROJECT
          SERVICE_NAME: $SERVICE_NAME
          DOCKER_COMPOSE_FILES: $DOCKER_COMPOSE_FILES
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DEPLOY_PATH,DOCKER_COMPOSE_PROJECT,SERVICE_NAME,DOCKER_COMPOSE_FILES
          script: |
            cd $DEPLOY_PATH
            chmod +x $DEPLOY_PATH/.deploy/deploy-single.sh
            $DEPLOY_PATH/.deploy/deploy-single.sh $DOCKER_COMPOSE_PROJECT $SERVICE_NAME "$DOCKER_COMPOSE_FILES"