name: Run Tests on PRs

on:
  pull_request:
    branches:
      - main

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
          cache: yarn

      - name: Build the environment file
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: .env.test
          output: .env

      - name: Install yarn
        run: corepack enable

      - name: Install packages
        run: yarn --prefer-offline --frozen-lockfile

      - name: Install playwright
        working-directory: .codeceptjs
        run: |
          yarn run playwright install
          yarn run playwright install-deps

      - name: Build and start the app
        run: NEXT_TELEMETRY_DISABLED=1 yarn build && yarn start & sleep 10 && echo 'Done waiting'

      - name: Run the tests
        working-directory: .codeceptjs
        run: yarn run codeceptjs run-multiple parallel